name: Testing

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "No testing required"
